# Generated by Django 5.1.3 on 2024-11-20 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_jobs', models.IntegerField()),
                ('m_machines', models.IntegerField()),
                ('problem_type', models.CharField(choices=[('FlowShop', 'FlowShop'), ('JobShop', 'JobShop')], max_length=20)),
                ('priority_rule', models.CharField(blank=True, choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO'), ('LPT', 'LPT'), ('SPT', 'SPT'), ('EDD', 'EDD'), ('JOHNSON', 'JOHNSON'), ('CDS', 'CDS')], max_length=20, null=True)),
                ('constraint', models.CharField(blank=True, choices=[('NO IDLE', 'NO IDLE'), ('NO WAIT', 'NO WAIT'), ('BLOCKING', 'BLOCKING'), ('SDST', 'SDST'), ('SIST', 'SIST'), ('AVAILABILITY', 'AVAILABILITY')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('arrival_time', models.IntegerField()),
                ('due_date', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.problem')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_time', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
            ],
            options={
                'unique_together': {('job', 'machine')},
            },
        ),
    ]
