# Generated by Django 5.1.3 on 2024-11-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='StartingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.machine')),
            ],
        ),
    ]
