# Generated by Django 5.0.3 on 2024-11-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_value_completiontime_ct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
