# Generated by Django 5.1.3 on 2024-11-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_completiontime_problem_processingtime_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemperformancemetrics',
            name='TU',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
